### PR TITLE
Fix indentation of subnet.erb

### PR DESCRIPTION
**Pull request by facastagnini**
**Before**
```
subnet 1.2.3.0 netmask 255.255.255.224 {
pool {
  range 1.2.3.2 1.2.3.10;
}
  option routers 1.2.3.4.1;
  option subnet-mask 255.255.255.224;
deny unkown-clients;

}
```

**After**
```
subnet 1.2.3.0 netmask 255.255.255.224 {
  pool {
    range 1.2.3.2 1.2.3.10;
  }
  option routers 1.2.3.4.1;
  option subnet-mask 255.255.255.224;
  deny unkown-clients;
}
```

### CODE REVIEW

**Comment by jmccann** [comment]
CI is failing, working to update it.  I think your changes may break some ChefSpec tests ... you can either wait for me to fix the CI or check locally.

**Comment by jmccann** [comment]
Could you rebase from master (fixed CI testing) and force push?

**Comment by facastagnini** [comment]
I am trying to fix the test, please hold on.

**Comment by facastagnini** [comment]
I end up with a messy branch, I will open a new PR.

**Pull request closed without merging**
